# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "u-mart-ivent-consis"
client_id = "7cde284a8481ae08320aa65cbc800b0d"
application_url = "https://77f9-2607-fea8-28e6-1d00-2472-4df-2779-f110.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products, read_inventory, write_inventory"

[auth]
redirect_urls = [
  "https://77f9-2607-fea8-28e6-1d00-2472-4df-2779-f110.ngrok-free.app/auth/callback",
  "https://77f9-2607-fea8-28e6-1d00-2472-4df-2779-f110.ngrok-free.app/auth/shopify/callback",
  "https://77f9-2607-fea8-28e6-1d00-2472-4df-2779-f110.ngrok-free.app/api/auth/callback",
  "https://77f9-2607-fea8-28e6-1d00-2472-4df-2779-f110.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "umarttesting.myshopify.com"
